
// for users REGISTER
export const GET_USERS_REGISTER_REQUEST = 'GET_USERS_REGISTER_REQUEST';
export const GET_USERS_REGISTER_FAILED = 'GET_USERS_REGISTER_FAILED'
export const GET_USERS_REGISTER_SUCCESS = 'GET_USERS_REGISTER_SUCCESS';

// FOR USER LOGIN
export const GET_LOGIN_USERS_REQUEST = 'GET_LOGIN_USERS_REQUEST';
export const GET_LOGIN_USERS_SUCCESS = 'GET_LOGIN_USERS_SUCCESS';
export const GET_LOGIN_USERS_FAILED = 'GET_LOGIN_USERS_FAILED';


// FOR COMPANY REGISTER
export const GET_LOGIN_COMPANY_FAILED = 'GET_LOGIN_COMPANY_FAILED';
export const GET_LOGIN_COMPANY_SUCCESS = 'GET_LOGIN_COMPANY_SUCCESS';
export const GET_LOGIN_COMPANY_REQUEST = 'GET_LOGIN_COMPANY_REQUEST';







